language: node_js
node_js:
- "lts/*"
before_install:
- npm install -g
- npm install -g bc19
script: npm test
branches:
  only:
  - master
notifications:
  slack:
    secure: LcuXaf7nR7RAQhl5JzY5O3Y2PJ6c9FqNYqjdX6anu1XVZlHKWraLbJsmfGmTfH7qCMvM72Ladtckqs5AnzCwqZoDWmVnPjh75kCysxgp+H5P7HYKuy76RrY9Zt5Ae5kg+pUZc/GCmxjIbPrF5HMXt6rBIQbq3CFcZZDY+6v4yQWzHvmpnla7CYbRL6Qf/HsWEkDTUJX6iIYTQabs3ntkcs1ktvKoAT863XrKek7APSjBQVA7xHpIyRFdObmWz1gNhkGgJRsWG5KVBCSA/4iu0q0Ke+CDklQrvm9gvo3MG6Y4Jz4vxFVbESslK9E1Fo4IXrgQWANfpFzI0HRVTGHdwFqYMuPCOMiFYZRU/mgFpFtThWEauVbuk569eJScRIlBPfbwjfB0sJCjKyla0TycXpJYf+vpEyep8ask9jB9VPOroCPgGpmupoI+PhwYvdBlX4owd8WixpeaFtNst9eX4S7xe2e8memtU79WD2MnUktM9oqWvfhyWnLh4QAnCdaQYoOrXXlhUiCnndUjYDLe6rPF56CA7gZMtafPJ+HjDv/P/JWhh9GsrzGI7dIwkWBJBtVpjq43HDw5KsA/p5EgzyELHSmXzqvIhNZSZ9H8c7hjWTB8dB0AfReQwfLzfj2DTojn1IgHd017JaDmBxeT7GLfpi1RA27ZFXTuu4dxSk4=
after_success: npm run coverage